export const reviewJsonSchema = {
  type: "object",
  additionalProperties: false,
  required: [
    "summary",
    "scoreTotal",
    "facts",
    "missingInfo",
    "imageObservations",
    "strengths",
    "weaknesses",
    "suggestions",
    "tags",
    "confidence",
    "ruleChecks",
  ],
  properties: {
    summary: { type: ["string", "null"] },
    scoreTotal: { type: ["number", "null"] },
    facts: {
      type: "object",
      additionalProperties: false,
      required: [
        "symbol",
        "direction",
        "openedAt",
        "closedAt",
        "netPnl",
        "rMultiple",
        "entryRuleName",
      ],
      properties: {
        symbol: { type: ["string", "null"] },
        direction: { type: ["string", "null"] },
        openedAt: { type: ["string", "null"] },
        closedAt: { type: ["string", "null"] },
        netPnl: { type: ["number", "null"] },
        rMultiple: { type: ["number", "null"] },
        entryRuleName: { type: ["string", "null"] },
      },
    },
    missingInfo: { type: "array", items: { type: "string" } },
    imageObservations: { type: "array", items: { type: "string" } },
    strengths: { type: "array", items: { type: "string" } },
    weaknesses: { type: "array", items: { type: "string" } },
    suggestions: { type: "array", items: { type: "string" } },
    tags: { type: "array", items: { type: "string" } },
    confidence: { type: ["number", "null"] },
    ruleChecks: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        required: ["checkItem", "result", "evidence", "comment", "scoreDelta"],
        properties: {
          checkItem: { type: "string" },
          result: { type: "string", enum: ["pass", "fail", "unknown"] },
          evidence: { type: ["string", "null"] },
          comment: { type: ["string", "null"] },
          scoreDelta: { type: ["number", "null"] },
        },
      },
    },
  },
};
